spring:
  application:
    name: service-turbine
server:
  port: 7000
turbine:
  aggregator:
    clusterConfig: default
  appConfig: eureka-ribbon-client, eureka-feign-client
  clusterNameExpression: new String ("default")
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka