spring:
  application:
    name: gateway-service
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9411
#  rabbitmq:
#    host: 119.23.228.243
#    username: admin
#    password: rabbitforliwenchao2791372
#    port: 5672
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
zuul:
  routes:
    api-a:
      path: /user-api/**
      serviceId: user-service
