spring:
  application:
    name: user-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      percentage: 1.0
#  rabbitmq:
#    host: 119.23.228.243
#    username: admin
#    password: rabbitforliwenchao2791372
#    port: 5672
server:
  port: 12000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka/
