spring:
  application:
    name: eureka-client
server:
  port: 9000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9527/eureka
  # instance:
  #  lease-expiration-duration-in-seconds:
  #  lease-renewal-interval-in-seconds:
